#!/bin/sh
#
# $Id$
#
# PROVIDE: dbmaster
# REQUIRE: LOGIN

. /etc/rc.subr

name="dbmaster"
rcvar="dbmaster_enable"

pidfile="/var/run/dbmaster"/dbmaster.pid
command="/usr/local/sbin/${name}"
command_args=""
procname="/usr/local/sbin/${name}"
command_interpreter="/usr/local/bin/perl"

load_rc_config ${name}

: ${pgagent_enable:="NO"}

run_rc_command "$1"
#EOF
