#!/bin/sh
#
# $Id$
#
# PROVIDE: pgagent
# REQUIRE: LOGIN

. /etc/rc.subr

name="pgagent"

rcvar="pgagent_enable"

pidfile="/var/run/pgdumper"/pgagent.pid
command="/usr/local/sbin/${name}"
command_args=""

load_rc_config ${name}

: ${pgagent_enable:="NO"}

run_rc_command "$1"
#EOF
