#!/bin/sh
#
# $Id$
#
# PROVIDE: pgmaster
# REQUIRE: LOGIN

. /etc/rc.subr

name="pgmaster"

rcvar="pgmaster_enable"

pidfile="/var/run/pgdumper"/pgmaster.pid
command="/usr/local/sbin/${name}"
procname="/usr/local/sbin/${name}"
command_interpreter="/usr/local/bin/perl"


load_rc_config ${name}

: ${pgmaster_enable:="NO"}

run_rc_command "$1"
#EOF
