#!/bin/sh
#
# $Id$
#
# PROVIDE: pgstore
# REQUIRE: LOGIN

. /etc/rc.subr

name="pgstore"

rcvar="pgstore_enable"

pidfile="/var/run/pgdumper"/pgstore.pid
command="/usr/local/sbin/${name}"
command_args=""

load_rc_config ${name}

: ${pgstore_enable:="NO"}

run_rc_command "$1"
#EOF
